import type { Metadata } from 'next'
import { Inter, Outfit } from 'next/font/google'
import './globals.css'

// const inter = Inter({ subsets: ['latin'] })
const outfit = Outfit({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`bg-black ${outfit.className}`}>
        {children}
      </body>
    </html>
  )
}
